#!/usr/bin/env bash
set -euo pipefail
MODEL_SLUG="${MODEL_SLUG:-g005_idm_temporal_masked_diffusion_luma_longctx_slim_fast80k_epoch1}"
CONFIG="${CONFIG:-configs/model/idm_temporal_masked_diffusion_d2e_luma_longctx_slim_fast80k_epoch1.yaml}"
OUTPUT_DIR="${OUTPUT_DIR:-outputs/idm_temporal_masked_diffusion_d2e_luma_longctx_slim_fast80k_epoch1}"
PROCESS_PATTERN="${PROCESS_PATTERN:-train_idm_temporal_masked_diffusion|run_g005_idm_temporal_luma_longctx_slim_fast80k_epoch1|run_g005_idm_temporal_raw96_family_presence_prefix}"
export MODEL_SLUG CONFIG OUTPUT_DIR PROCESS_PATTERN
exec bash scripts/run_g005_idm_temporal_raw96_family_presence_prefix.sh
